const IS_PROD = process.env.NODE_ENV === 'production';
const IS_DEPLOY_GROUP_PROD = process.env.DEPLOY_GROUP === 'production';

const API_HOST = process.env.NEXT_PUBLIC_API_HOST;
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL;
const KAKAO_JAVASCRIPT_KEY = process.env.NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY;
const GOOGLE_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
const SENTRY_DSN = process.env.NEXT_PUBLIC_SENTRY_DSN;
const GOOGLE_ANALYTICS_G_TAG = process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_G_TAG;

export {
  IS_PROD,
  IS_DEPLOY_GROUP_PROD,
  API_HOST,
  SITE_URL,
  KAKAO_JAVASCRIPT_KEY,
  GOOGLE_CLIENT_ID,
  SENTRY_DSN,
  GOOGLE_ANALYTICS_G_TAG,
};
